### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by vandatgsts** [Nguyen-Duy-Son/Hit-Flutter#1]
-  các thành phần giống nhau như các widget trong tiện tích ở b1 thì có thể tách ra 1 widget riêng rồi truyền content vào
- cái nào "const" được thì nhớ để "const" nó sẽ tăng performance 
bài 1:
 phần ảnh calendar đang nằm cùng 1 row với ngày ..., trong khi ảnh gốc nó nằm nhếch lên trên góc trái và có 1 nửa ở ngoài-> tìm hiểu về stack để thực hiện nhá
-  bài 2 các widget ở dưới thằng cha width có 90 mà tổng của các widget con =110 >90 rồi 
![image](https://github.com/Nguyen-Duy-Son/Hit-Flutter/assets/87601035/d8555b02-b83e-42a3-b8a1-3d593c7ab102)

**Comment by Nguyen-Duy-Son** [comment]
em đã sửa lại rồi ạ.
